language: python

compiler:
  - c++

python:
  - 2.7

before_install:
  - git submodule init
  - git submodule update

install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq cmake cmake-curses-gui libargtable2-0 libargtable2-dev libsndfile1 libsndfile1-dev libmpg123-0 libmpg123-dev libfftw3-3 libfftw3-dev liblapack-dev libhdf5-serial-dev libhdf5-serial-1.8.4
  - pip install -r requirements.txt

before_script:
  - 
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX=$VIRTUAL_ENV ..
  - export LD_LIBRARY_PATH=$VIRTUAL_ENV/lib

script:
  - make
  - make install
  - make doctest

branches:
  only:
    - master
    - develop
